parameters:
  name: ''
  vmImage: ''
  toolchain: 'stable'

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  variables:
    tc: ${{ parameters.toolchain }}
  steps: 
  - bash: |
      curl -o rustup-init.sh https://sh.rustup.rs -sSf
      sh rustup-init.sh --default-toolchain $(tc) -y
    displayName: 'Install rust'
  - bash: |
      source $HOME/.cargo/env
      cargo build --release
      cargo test
    displayName: 'Build eilpx'
  - task: CopyFiles@2
    inputs:
      contents: 'target/release/eilpx'
      targetfolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    condition: eq('${{ parameters.toolchain }}', 'stable')
    inputs:
      pathtoPublish: 'target/release/eilpx'
      artifactName: 'eilpx-$(Build.BuildNumber)-$(Agent.OS)'