# azure pipelines configs derived from Erk-/rsget
# https://github.com/Erk-/rsget/blob/master/azure-pipelines.yml

jobs:
- template: 'azure-template.yml'
  parameters:
    name: 'macOS_stable'
    vmImage: 'xcode9-macos10.13'
    toolchain: 'stable'

- template: 'azure-template.yml'
  parameters:
    name: 'macOS_nightly'
    vmImage: 'xcode9-macos10.13'
    toolchain: 'nightly'

- template: 'azure-template.yml'
  parameters:
    name: 'Linux_stable'
    vmImage: 'ubuntu-16.04'
    toolchain: 'stable'

- template: 'azure-template.yml'
  parameters:
    name: 'Linux_nightly'
    vmImage: 'ubuntu-16.04'
    toolchain: 'nightly'

- template: 'azure-template-win.yml'
  parameters:
    name: 'Windows_stable'
    vmImage: 'vs2017-win2016'
    toolchain: 'stable'

- template: 'azure-template-win.yml'
  parameters:
    name: 'Windows_nightly'
    vmImage: 'vs2017-win2016'
    toolchain: 'nightly'