# azure pipelines configs derived from Erk-/rsget
# https://github.com/Erk-/rsget/blob/master/azure-pipelines.yml

trigger:
  branches:
    include:
      - refs/heads/master
      - refs/heads/azure-pipelines
      - refs/tags/*

jobs:
- template: 'azure-template.yml'
  parameters:
    name: 'macOS_stable'
    vmImage: 'xcode9-macos10.13'
    toolchain: 'stable'

- template: 'azure-template.yml'
  parameters:
    name: 'macOS_nightly'
    vmImage: 'xcode9-macos10.13'
    toolchain: 'nightly'

- template: 'azure-template.yml'
  parameters:
    name: 'Linux_stable'
    vmImage: 'ubuntu-16.04'
    toolchain: 'stable'

- template: 'azure-template.yml'
  parameters:
    name: 'Linux_nightly'
    vmImage: 'ubuntu-16.04'
    toolchain: 'nightly'

- template: 'azure-template-win.yml'
  parameters:
    name: 'Windows_stable'
    vmImage: 'vs2017-win2016'
    toolchain: 'stable'

- template: 'azure-template-win.yml'
  parameters:
    name: 'Windows_nightly'
    vmImage: 'vs2017-win2016'
    toolchain: 'nightly'

- job: Publish_release
  dependsOn:
  - macOS_stable
  - Linux_stable
  - Windows_stable
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: "Download MacOS Artifacts"
    inputs:
      buildType: 'current'
      artifactName: 'eilpx-$(Build.BuildNumber)-Darwin'
      downloadPath: '$(build.artifactStagingDirectory)'
  - bash: |
      cd $(build.artifactStagingDirectory)/eilpx-$(Build.BuildNumber)-Darwin/
      mv eilpx $(build.artifactStagingDirectory)/eilpx-osx-x86_64
      rm -rf $(build.artifactStagingDirectory)/eilpx-$(Build.BuildNumber)-Darwin/
    displayName: "Move MacOS Artifacts"

  - task: DownloadBuildArtifacts@0
    displayName: "Download Linux Artifacts"
    inputs:
      buildType: 'current'
      artifactName: 'eilpx-$(Build.BuildNumber)-Linux'
      downloadPath: '$(build.artifactStagingDirectory)'
  - bash: |
      cd $(build.artifactStagingDirectory)/eilpx-$(Build.BuildNumber)-Linux/
      mv eilpx $(build.artifactStagingDirectory)/eilpx-linux-x86_64
      rm -rf $(build.artifactStagingDirectory)/eilpx-$(Build.BuildNumber)-Linux/
    displayName: "Move Linux Artifacts"

  - task: DownloadBuildArtifacts@0
    displayName: "Download Windows Artifacts"
    inputs:
      buildType: 'current'
      artifactName: 'eilpx-$(Build.BuildNumber)-Windows_NT'
      downloadPath: '$(build.artifactStagingDirectory)'
  - bash: |
      cd $(build.artifactStagingDirectory)/eilpx-$(Build.BuildNumber)-Windows_NT/
      mv eilpx.exe $(build.artifactStagingDirectory)/eilpx-windows-x86_64.exe
      rm -rf $(build.artifactStagingDirectory)/eilpx-$(Build.BuildNumber)-Windows_NT/
    displayName: "Move Windows Artifacts"

  - bash: |
      echo "build.artifactStagingDirectory $(build.artifactStagingDirectory)"
      ls $(build.artifactStagingDirectory)

      echo "build.binariesDirectory $(build.binariesDirectory)"
      ls $(build.binariesDirectory)

      echo "build.sourcesDirectory $(build.sourcesDirectory)"
      ls $(build.sourcesDirectory)

      echo "build.stagingDirectory $(build.stagingDirectory)"
      ls $(build.stagingDirectory)

  - task: GithubRelease@0
    inputs:
      gitHubConnection: 'drklee3-gh'
      repositoryName: 'drklee3/eilpx'
      action: 'create' # Options: create, edit, discard
      target: '$(build.sourceVersion)' # Required when action == create || action == edit
      tagSource: 'auto' # Required when action == create. Options: auto, manual
      tag: $(tagName) # Required when action == edit || action == discard || tagSource == manual
      assets: '$(build.artifactStagingDirectory)/*'
      addChangeLog: true # Optional